MiPrimerMVC/Controllers/CalculadoraRomanaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Domain.Services;
using MiPrimerMVC.Models;
using Ninject;

namespace MiPrimerMVC.Controllers
{
    public class CalculadoraRomanaController : Controller
    {
        readonly ICalculadora _calc;
        readonly IReadOnlyRepository _readOnlyRepository;
        readonly IWriteOnlyRepository _writeOnlyRepository;

        public CalculadoraRomanaController(ICalculadora calc,IReadOnlyRepository readOnlyRepository, IWriteOnlyRepository writeOnlyRepository)
        {
            _calc = calc;
            _readOnlyRepository = readOnlyRepository;
            _writeOnlyRepository = writeOnlyRepository;
        }

        //
        // GET: /Calculadora/
        public ActionResult Index()
        {
            var calculadora = new Calculadora
            {
                Operaciones = _readOnlyRepository.GetAll<Operaciones>().ToList()
            };
            return View(calculadora);
        }


        [HttpPost]
        public ActionResult Index(Calculadora calculadora)
        {
            
            var operacion = new Operaciones("");
            if (calculadora.Entrada.Contains("-"))
            {
                operacion.Operador = "-";
                operacion.Numero1 = calculadora.Entrada.Split('-')[0];
                operacion.Numero2 = calculadora.Entrada.Split('-')[1];
                operacion.Resultado = _calc.Resta(calculadora.Entrada);
            }
            else if (calculadora.Entrada.Contains("+"))
            {
                operacion.Operador = "+";
                operacion.Numero1 = calculadora.Entrada.Split('+')[0];
                operacion.Numero2 = calculadora.Entrada.Split('+')[1];
                operacion.Resultado = _calc.Suma(calculadora.Entrada);
            }

            calculadora.Salida = operacion.Resultado;

            var createdOperation = _writeOnlyRepository.Create(operacion);
            calculadora.Operaciones = _readOnlyRepository.GetAll<Operaciones>().ToList();

            return View(calculadora);
        }
        

        //GET: /CalculadoraRomana/Detalle/{id}
        public ActionResult Detalle(long id)
        {
            var operacion = _readOnlyRepository.GetById<Operaciones>(id);
            return View(operacion);
        }

    }

    public class CalculadoraRomana : ICalculadora
    {
        // I + II
        public string Suma(string value)
        {
            return "III";
        }

        // VII - II
        public string Resta(string value)
        {
            return "V";
        }
    }

    public class CalculadoraNormal : ICalculadora
    {
        public string Suma(string value)
        {
            return "3";
        }

        public string Resta(string value)
        {
            return "5";
        }
    }

    public interface ICalculadora
    {
        string Suma(string value);
        string Resta(string value);
    }
}

MiPrimerMVC/Views/CalculadoraRomana/Detalle.cshtml
@model Domain.Entities.Operaciones

@{
    ViewBag.Title = "Detalle de Operacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle de Operacion</h2>
<div class="row">
    @Html.LabelFor(x=>x.Id)
    @Html.ValueFor(x=>x.Id)
    @Html.LabelFor(x => x.Numero1)
    @Html.ValueFor(x => x.Numero1)
    @Html.LabelFor(x => x.Numero2)
    @Html.ValueFor(x => x.Numero2)
    @Html.LabelFor(x => x.Operador)
    @Html.ValueFor(x => x.Operador)
    @Html.LabelFor(x => x.Resultado)
    @Html.ValueFor(x => x.Resultado)
</div>

MiPrimerMVC/Views/CalculadoraRomana/Division.cshtml
@model dynamic

@{
    ViewBag.Title = "Calculadura Romana - Division de Numeros Romanos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calculadura Romana - Division de Numeros Romanos</h2>

MiPrimerMVC/Views/CalculadoraRomana/Index.cshtml
@using Domain.Entities
@using MiPrimerMVC.Controllers
@using MiPrimerMVC.Models
@model MiPrimerMVC.Models.Calculadora

@{
    ViewBag.Title = "Calculadora Romana";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calculadora HOLA Romana</h2>

@using (Html.BeginForm("Index","CalculadoraRomana",null,FormMethod.Post,new {@class="form-horizontal"})) {

    @Html.LabelFor(x=>x.Entrada)
    @Html.TextBoxFor(x=>x.Entrada,new {@class="form-control"})
    <button class="btn btn-default" type="submit">Calcular</button>
}

@{
    const string newyork = ".newyork";
}
<div class="row" id=@newyork>
    <p>
        @Html.LabelFor(x => x.Salida)
        @Html.ValueFor(x => x.Salida)
    </p>    
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>    
                <th>Numero 1</th>
                <th>Operador</th>
                <th>Numero 2</th>
                <th>Resultado</th>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>@*
            @foreach (Operaciones operacion in Model.Operaciones)
            {
                <tr>
                    <td>
                        @Html.ActionLink(@operacion.Id.ToString(),"Detalle",new {@id = @operacion.Id},null)
                    </td>
                    <td>@operacion.Numero1</td>
                    <td>@operacion.Operador</td>
                    <td>@operacion.Numero2</td>
                    <td>@operacion.Resultado</td>
                    <td>
                        <button type="button">Eliminar</button>
                        <button type="button">Editar</button>
                    </td>
                </tr>
            }
        *@
        </tbody>
    </table>
</div>

MiPrimerMVC/Views/CalculadoraRomana/Multiplicacion.cshtml
@model dynamic

@{
    ViewBag.Title = "Calculadora Romana - Multiplcacion de Numeros Romanas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calculadora Romana - Multiplcacion de Numeros Romanas</h2>

MiPrimerMVC/Views/CalculadoraRomana/Resta.cshtml
@model dynamic

@{
    ViewBag.Title = "Calculadora Romana - Restar Numeros Romanos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calculadora Romana - Restar Numeros Romanos</h2>

MiPrimerMVC/Views/CalculadoraRomana/Suma.cshtml
@model dynamic

@{
    ViewBag.Title = "Calculadora Romana - Sumar Numeros Romanos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calculadora Romana - Sumar Numeros Romanos</h2>