MiPrimerMVC/Controllers/ClassifiedsController.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using System.Windows.Forms;
using Domain.Entities;
using Domain.Services;
using MiPrimerMVC.Models;
using MiPrimerMVC.ValidationAttributes;
using Twilio;

namespace MiPrimerMVC.Controllers
{
    public class ClassifiedsController: Controller
    {
         readonly IReadOnlyRepository _readOnlyRepository;
        readonly IWriteOnlyRepository _writeOnlyRepository;
        public ClassifiedsController(IReadOnlyRepository readOnlyRepository, IWriteOnlyRepository writeOnlyRepository)
        {
            _readOnlyRepository = readOnlyRepository;
            _writeOnlyRepository = writeOnlyRepository;
        }

        [Authorize]
        public ActionResult CreateClassified()
        {
            return View(new ClassifiedModel());
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateClassified(ClassifiedModel model)
        {
            if (ModelState.IsValid)
            {
                        var validate = new IValidate();
                        var user = _readOnlyRepository.FirstOrDefault<AccountLogin>(x => x.Email == HttpContext.User.Identity.Name);
                        var classifiedsList = user.AccountClassifieds.ToList();

                        classifiedsList.Add(new Classifieds(model.Category, model.Article, model.ArticleModel, model.Location,
                          model.Price, model.Description, user.Email, model.UrlImage, model.UrlImage1, model.UrlImage2, model.UrlImage3, model.UrlImage4, validate.Embed(model.UrlVideo)));

                        user.AccountClassifieds = classifiedsList;
                        _writeOnlyRepository.Update(user);

                var notifyList = _readOnlyRepository.GetAll<Subscriptions>().Where(x => x.Following == user.Id && !x.Archived);
                
                if(!notifyList.Any())
                foreach (var x in notifyList)
                {
                    var userToBeNotify = _readOnlyRepository.FirstOrDefault<AccountLogin>(z => z.Id == x.Follower);
                    var list = userToBeNotify.Notifications.ToList();
                    list.Add(new Notifications(user.Email,model.Article,"Classi"));
                    userToBeNotify.Notifications = list;
                    _writeOnlyRepository.Update(userToBeNotify);
                }

                //check
                MessageBox.Show("Classified added successfully");

            }        

            return View("CreateClassified",model);
        }

        [Authorize]
        public ActionResult MyClassifieds(long id=0)
        {
            var mcModel = new ClassiModel();
            if (id != 0)
            {
                mcModel.classifiedForDetail = _readOnlyRepository.FirstOrDefault<Classifieds>(z => z.Id == id);

            }
          
            var x = _readOnlyRepository.FirstOrDefault<AccountLogin>(z=>z.Email==HttpContext.User.Identity.Name && !z.Archived);
            mcModel.myClassifiedsList= x.AccountClassifieds.Where(z=>!z.AdminArchived && !z.Archived).ToList();
            mcModel.myClassifiedsListArchived = x.AccountClassifieds.Where(z => !z.AdminArchived && z.Archived).ToList();
           
            return View(mcModel);
        }

        public static string EmailReceiver="";
        public ActionResult Detailed(long id)
        {
            var classified = _readOnlyRepository.GetById<Classifieds>(id);
            var classiModel = new ClassiModel();
            classiModel.classifiedForDetail = classified;
            EmailReceiver = classiModel.classifiedForDetail.Email;
            var user = _readOnlyRepository.FirstOrDefault<AccountLogin>(x => x.Email == EmailReceiver);
            classiModel.ContactInfo = user.UserInfo;
            classiModel.classifiedForDetail.Visited++;
            _writeOnlyRepository.Update(classiModel.classifiedForDetail);

            return View(classiModel);
        }

        [HttpPost]
        public ActionResult Detailed(ClassiModel model, string id)
        {
                    
                    var user = _readOnlyRepository.FirstOrDefault<AccountLogin>(x => x.Email == EmailReceiver);
                    var messageList = user.AccountMessages.ToList();
                    messageList.Add(new Messages(model.sendEmail.Email, model.sendEmail.Name, model.sendEmail.Message, "Classified|Info"));
                    user.AccountMessages = messageList;
                    SendSms(model.sendEmail.Message, EmailReceiver, user.Name, id, user.UserInfo.Cellphone);
                    _writeOnlyRepository.Update(user);
                   // MailTo.SendSimpleMessage(EmailReceiver, model.sendEmail.Name, model.sendEmail.Message);
                  
            //check
            MessageBox.Show("Email sent successfully");
            
            return RedirectToAction("AllClassifieds");
        }

        [Authorize]
        public ActionResult ManageClassifieds(long id)
        {
            var mClassified = new ManageClassifiedsModel();
            mClassified.ClassifiedToBeEdited = _readOnlyRepository.FirstOrDefault<Classifieds>(x => x.Id == id);


            return View(mClassified);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ManageClassifieds(ManageClassifiedsModel model)
        {
            
            if (ModelState.IsValid)
            {
                if (model.ClassifiedToBeEdited.Article != model.Article || model.Article.Trim() == "")
                    model.ClassifiedToBeEdited.Article = model.Article;

                if (model.ClassifiedToBeEdited.ArticleModel != model.ArticleModel)
                    model.ClassifiedToBeEdited.ArticleModel = model.ArticleModel;

                if (model.ClassifiedToBeEdited.Description != model.Description || model.Description.Trim() == "")
                    model.ClassifiedToBeEdited.Description = model.Description;

                if (model.ClassifiedToBeEdited.Price != model.Price)
                    model.ClassifiedToBeEdited.Price = model.Price;

                model.ClassifiedToBeEdited.UrlImage = model.UrlImage;
                model.ClassifiedToBeEdited.UrlImage1 = model.UrlImage1;
                model.ClassifiedToBeEdited.UrlImage2 = model.UrlImage2;
                model.ClassifiedToBeEdited.UrlImage3 = model.UrlImage3;
                model.ClassifiedToBeEdited.UrlImage4 = model.UrlImage4;

                if (model.ClassifiedToBeEdited.Location != model.Location || model.Location.Trim()!="")
                    model.ClassifiedToBeEdited.Location = model.Location;

                if (model.ClassifiedToBeEdited.Category != model.Category)
                    model.ClassifiedToBeEdited.Category = model.Category;

                if (model.ClassifiedToBeEdited.UrlVideo != model.UrlVideo || model.UrlVideo.Trim() == "")
                    model.ClassifiedToBeEdited.UrlVideo = model.UrlVideo;

                _writeOnlyRepository.Update(model.ClassifiedToBeEdited);

            } ModelState.AddModelError("", "Something went wrong.");

            return RedirectToAction("MyClassifieds");
        }

        [Authorize]
        public ActionResult Archive(long id)
        {
            var classifiedToBeArchived = _readOnlyRepository.FirstOrDefault<Classifieds>(x => x.Id == id);
            classifiedToBeArchived.Archive();
            _writeOnlyRepository.Update(classifiedToBeArchived);

            return RedirectToAction("MyClassifieds");
        }

        [Authorize]
        public ActionResult Activate(long id)
        {
            var classifiedToBeActivated = _readOnlyRepository.FirstOrDefault<Classifieds>(x => x.Id == id);
            classifiedToBeActivated.Activate();
            _writeOnlyRepository.Update(classifiedToBeActivated);

            return RedirectToAction("MyClassifieds");
        }

        public ActionResult Report(long id)
        {
            var classifiedToBeReported = _readOnlyRepository.FirstOrDefault<Classifieds>(x => x.Id==id);
            var adminUser = _readOnlyRepository.FirstOrDefault<AccountLogin>(x => x.Id == 1);
            var list = adminUser.Notifications.ToList();
            list.Add(new Notifications(classifiedToBeReported.Email, classifiedToBeReported.Article, "Report"));
            adminUser.Notifications = list;
            _writeOnlyRepository.Update(adminUser); 


            return RedirectToAction("Detailed", new{id});
        }
        public ActionResult AllClassifieds(string category="All")
        {
            var allModel = new ClassiModel();
            switch (category)
            {
                case "All": allModel.myClassifiedsList = _readOnlyRepository.GetAll<Classifieds>().Where(x=>!x.Archived && !x.AdminArchived).ToList();
                    break;
                case "Auto": allModel.myClassifiedsList = _readOnlyRepository.GetAll<Classifieds>().Where(x => x.Category == "Automoviles" && !x.Archived && !x.AdminArchived).ToList();
                    break;
                case "Inst": allModel.myClassifiedsList = _readOnlyRepository.GetAll<Classifieds>().Where(x => x.Category == "Instruments" && !x.Archived && !x.AdminArchived).ToList();
                    break;
                case "VGC": allModel.myClassifiedsList = _readOnlyRepository.GetAll<Classifieds>().Where(x => x.Category == "VG. Consoles" && !x.Archived && !x.AdminArchived).ToList();
                    break;
                case "Tech": allModel.myClassifiedsList = _readOnlyRepository.GetAll<Classifieds>().Where(x => x.Category == "Technology" && !x.Archived && !x.AdminArchived).ToList();
                    break;
            }
           
            return View(allModel);
        }
        
        public ActionResult AdvancedSearch()
        {
            var cAdvancedSearch = new ClassiModel
            {

MiPrimerMVC/Views/Classifieds/ManageClassifieds.cshtml
@model MiPrimerMVC.Models.ManageClassifiedsModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}

<html>
<head>
    <title>title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" type="text/css" />
</head>
<body>
    @{
        var dropdownItems = new List<SelectListItem>();
        dropdownItems.AddRange(new[]
            {
                new SelectListItem {Text = "Automoviles"},
                new SelectListItem {Text = "Instruments"},
                new SelectListItem {Text = "VG. Consoles"},
                new SelectListItem {Text = "Technology"}
            });
        ViewData.Add("DropDownItems", dropdownItems);

        var dropdownItems2 = new List<SelectListItem>();
        dropdownItems2.AddRange(new[]
            {
                new SelectListItem {Text = "Sale"},
                new SelectListItem {Text = "Rent"}
            });
        ViewData.Add("DropDownItems2", dropdownItems2);
    }
    <div class="container-960 innerT">
        <div class="widget widget-heading-simple widget-body-gray">
            <div class="widget-body"><p class="lead center margin-none"><i class="fa fa-newspaper-o"></i> Create a Classified</p></div>
        </div>
    </div>
    @using (Html.BeginForm("CreateClassified", "Classifieds", null, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <fieldset>
            <!--Title-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Old Title @Model.ClassifiedToBeEdited.Article</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.Article, new { @class = "form-control", placeholder = "New Article Title" })
                </div>
            </div>
            <!--END Title-->
            <!--Type-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Old Business Type @Model.ClassifiedToBeEdited.ArticleModel</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(x => x.ArticleModel, ViewData["DropDownItems2"] as List<SelectListItem>, new { @class = "dropdown", @style = "width:150px" })
                </div>
            </div>
            <!--End Type-->
            <!--Category-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Old Category @Model.ClassifiedToBeEdited.Category</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(x => x.Category, ViewData["DropDownItems"] as List<SelectListItem>, new { @class = "dropdown", @style = "width:150px" })
                </div>
            </div>
            <!-- End Category-->
            <!--Location-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Old Location @Model.ClassifiedToBeEdited.Article</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.Location, new { @class = "form-control", placeholder = "State | Country" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.Location)</label>

                </div>
            </div>
            <!--END Location-->
            <!--Price-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Old Price @Model.ClassifiedToBeEdited.Price</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.Price, new { @class = "form-control", placeholder = "$ 00.00" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.Price)</label>

                </div>
            </div>
            <!--END Price-->
            <!--img URL-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Image URL</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.UrlImage, new { @class = "form-control", placeholder = "Image URL here" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.UrlImage)</label>
                </div>
                <label class="col-lg-2 control-label">Image URL1</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.UrlImage1, new { @class = "form-control", placeholder = "Image URL1 here*" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.UrlImage1)</label>
                </div>
                <label class="col-lg-2 control-label">Image URL2</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.UrlImage2, new { @class = "form-control", placeholder = "Image URL2 here*" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.UrlImage2)</label>
                </div>
                <label class="col-lg-2 control-label">Image URL3</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.UrlImage3, new { @class = "form-control", placeholder = "Image URL3 here*" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.UrlImage3)</label>
                </div>
                <label class="col-lg-2 control-label">Image URL4</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.UrlImage4, new { @class = "form-control", placeholder = "Image URL4 here*" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.UrlImage4)</label>
                </div>
            </div>
            <!--END img URL-->
            <!--vd URL-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Video URL</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(x => x.UrlVideo, new { @class = "form-control", placeholder = "New Video URL here" })
                </div>
            </div>
            <!--END vd URL-->
            <!--Description-->
            <div class="form-group">
                <label class="col-lg-2 control-label">Write New Description</label>
                <div class="col-lg-10">
                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control", rows = "3" })
                    <label style="color: red">@Html.ValidationMessageFor(x => x.Description)</label>

                    <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
                </div>
            </div>
            <!--End Description-->
            <button class=" btn " type="submit">Create&nbsp;&nbsp;&nbsp;<i class=" icon-chevron-sign-right"></i></button>

        </fieldset>
    }

</body>
</html>

MiPrimerMVC/Views/Classifieds/MyClassifieds.cshtml
@model MiPrimerMVC.Controllers.ClassifiedsController.ClassiModel

@{
    ViewBag.Title = "title";
    Layout = Context.User.Identity.Name == "jmibarrad@gmail.com" ? "~/Views/Shared/_Layout3.cshtml" : "~/Views/Shared/_Layout2.cshtml";
}
<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                My Classifieds
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                </span>
            </header>
            <div class="panel-body">
                <ul id="filters" class="media-filter">
                    <li><a href="#" data-filter="*"> All</a></li>
                    <li><a href="#" data-filter=".Automoviles">Automoviles</a></li>
                    <li><a href="#" data-filter=".Instruments">Instruments</a></li>
                    <li><a href="#" data-filter=".VGConsoles">Video</a></li>
                    <li><a href="#" data-filter=".Technology">Technology</a></li>
                </ul>
                <div class="span10">
                    <h2>Active Classifieds</h2>
                </div>
                <div id="gallery" class="media-gal">
                    @foreach (var x in @Model.myClassifiedsList) { 
                        <div class="@x.Category item ">
                            <a ><img src="@x.UrlImage" alt="" /></a>
                            @Html.ActionLink(@x.Article,"ManageClassifieds","Classifieds",new{@id=x.Id},null)      <span>@Html.ActionLink("Archive", "Archive", "Classifieds", new { @id = x.Id }, new { @class = "btn btn-danger" })</span>

                        </div>
                    }
                </div>
                <div class="span10">
                    <h2>Archived Classifieds</h2>
                </div>
                <div id="gallery" class="media-gal">
                    @foreach (var x in @Model.myClassifiedsListArchived)
                    {
                        <div class="@x.Category item ">
                            <a><img src="@x.UrlImage" alt="" /></a>
                            @Html.ActionLink(@x.Article, "ManageClassifieds", "Classifieds", new { @id = x.Id }, null)     <span>@Html.ActionLink("Activate", "Activate", "Classifieds", new { @id = x.Id }, new { @class = "btn btn-success" })</span>

                        </div>
                    }
                </div>
                <div class="col-md-12 text-center clearfix">
                    <ul class="pagination">
                        <li><a href="#">«</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                </div>
                @*<!-- Modal -->
                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">Edit Classified</h4>
                                </div>
                                @using (Html.BeginForm("MyClassifieds", "Classifieds", null, FormMethod.Post)) {
                                    <div class="modal-body row">
                                        <div class="col-md-5 img-modal">
                                            <img src="images/gallery/image1.jpg" alt="">
                                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> Edit Image</a>
                                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-eye"></i> View Full Size</a>
                                            <p class="mtop10"><strong>Article Name:</strong>@Html.ValueFor(x=>x.Price)</p>
                                            <p><strong>File Type:</strong> jpg</p>
                                            <p><strong>Resolution:</strong> 300x200</p>
                                            <p><strong>Uploaded By:</strong> <a href="#">ThemeBucket</a></p>
                                        </div>
                                        <div class="col-md-7">
                                            <div class="form-group">
                                                <label> Name</label>
                                                <input id="name" value="img01.jpg" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label> Tittle Text</label>
                                                <input id="title" value="awesome image" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label> Description</label>
                                                <textarea rows="2" class="form-control"></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label> Link URL</label>
                                                <input id="link" value="images/gallery/img01.jpg" class="form-control">
                                            </div>
                                            <div class="pull-right">
                                                <button class="btn btn-danger btn-sm" type="button">Delete</button>
                                                <button class="btn btn-success btn-sm" type="submit">Save changes</button>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <!-- modal -->*@
                </div>
            </section>
        </div>
    </div>

    <script src="~/adminX/js/jquery-1.10.2.min.js"></script>
    <script src="~/adminX/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="~/adminX/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/adminX/js/bootstrap.min.js"></script>
    <script src="~/adminX/js/modernizr.min.js"></script>
    <script src="~/adminX/js/jquery.nicescroll.js"></script>
    <script src="~/adminX/js/jquery.isotope.js"></script>
    <!--common scripts for all pages-->
    <script src="~/adminX/js/scripts.js"></script>
    <script type="text/javascript">
        $(function () {
            var $container = $('#gallery');
            $container.isotope({
                itemSelector: '.item',
                animationOptions: {
                    duration: 750,
                    easing: 'linear',
                    queue: false
                }
            });

            // filter items when filter link is clicked
            $('#filters a').click(function () {
                var selector = $(this).attr('data-filter');
                $container.isotope({ filter: selector });
                return false;
            });
        });
    </script>