MiPrimerMVC/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Configuration;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using Domain.Entities;
using Domain.Services;
using MiPrimerMVC.ValidationAttributes;

namespace MiPrimerMVC.Controllers
{
    public class FAQController : Controller
    {
        readonly IReadOnlyRepository _readOnlyRepository;
        readonly IWriteOnlyRepository _writeOnlyRepository;
        public FAQController(IReadOnlyRepository readOnlyRepository, IWriteOnlyRepository writeOnlyRepository)
        {
            _readOnlyRepository = readOnlyRepository;
            _writeOnlyRepository = writeOnlyRepository;
        }

        [HttpGet]
        public ActionResult FAQ()
        {
            var questionsList = _readOnlyRepository.GetAll<Questions>().Where(x=>!x.Archived).ToList();
            var questionModel = new QuestionModel();
            questionsList.Reverse();
            questionModel.QuestionList = questionsList;

            return View(questionModel);
        }

        [HttpPost]
        public ActionResult FAQ(QuestionModel model)
        {
          
            var questionToBePushed = new Questions(model.QuestionText,model.Email, model.Name);

             _writeOnlyRepository.Create(questionToBePushed);
        //check
                    MessageBox.Show("Question Added Succesfully");
            
            var questionsList = _readOnlyRepository.GetAll<Questions>().Where(x=>!x.Archived).ToList();
            questionsList.Reverse();
            model.QuestionList = questionsList;

            return View(model);
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult ManageFaq()
        {
            var questionsList = _readOnlyRepository.GetAll<Questions>().Where(x=>!x.Archived).ToList();
            var questionModel = new QuestionModel();
            questionsList.Reverse();
            questionModel.QuestionList = questionsList;
            return View(questionModel);
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult AnswerQuestions(long id)
        {
            var questionToBeAnswered = _readOnlyRepository.FirstOrDefault<Questions>(x => x.Id == id && !x.Archived);
            var answermodel = new AnswerModel {FaqQuestion = questionToBeAnswered};

            return View(answermodel);
        }

        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        public ActionResult AnswerQuestions(AnswerModel model, long id)
        {
            var questionToBeSaved = _readOnlyRepository.FirstOrDefault<Questions>(x=>x.Id==id);
            var list = questionToBeSaved.QuestionAnswers.ToList();
            list.Add(new Answers(model.AnswerText));
            questionToBeSaved.QuestionAnswers = list;
            _writeOnlyRepository.Update(questionToBeSaved);

            return RedirectToAction("ManageFaq");
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult ArchiveQuestion(long id)
        {
            var questionToBeArchived = _readOnlyRepository.FirstOrDefault<Questions>(x => x.Id == id);
            questionToBeArchived.Archive();
            _writeOnlyRepository.Update(questionToBeArchived);

            return RedirectToAction("ManageFaq");
        }

    }


    public class QuestionModel
    {
        public List<Questions> QuestionList { get; set; }

        [Required(ErrorMessage = "Question is required")]
        [DataType(DataType.MultilineText)]
        [DescriptionValidation(MinimumAmountOfWords = 3, MaximumAmountOfCharacters = 255,
            ErrorMessage = "Question must contain a minimum of 3 words and a maximum of 255 characters.")]
        public string QuestionText { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email is not valid.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [DataType(DataType.Text)]
        [StringLength(50, ErrorMessage = "First name should be between 3 and 50 characters.", MinimumLength = 3)]
        public string Name { get; set; }
    }

    public class AnswerModel
    {
        [Required(ErrorMessage = "Name is required")]
        [DataType(DataType.Text)]
        [StringLength(50, ErrorMessage = "First name should be between 1 and 50 characters.", MinimumLength = 1)]
        public string AnswerText { get; set; }
        public Questions FaqQuestion { get; set; }
    }
}

MiPrimerMVC/Views/FAQ/AnswerQuestions.cshtml
@model MiPrimerMVC.Controllers.AnswerModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Manage FAQ
            </header>
            <div class="panel-body">
                <div><p>Question: @Model.FaqQuestion.QuestionText   
                    @using(Html.BeginForm("AnswerQuestions","FAQ",new{@id=Model.FaqQuestion.Id},FormMethod.Post,new{@class="form-horizontal adminex-form"})){
                
                        <div class="form-group">
                            @Html.TextAreaFor(x => x.AnswerText, new { @class = "form-control", rows = "3" })
                            <label style="color: red">@Html.ValidationMessageFor(x => x.AnswerText)</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Answer</button>
                    }
                </div>
             </div>
        </section>
    </div>
</div>

MiPrimerMVC/Views/FAQ/ManageFaq.cshtml
@model MiPrimerMVC.Controllers.QuestionModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}

<div class="panel">
    <div class="panel-body">
        <h1 class="text-center cmnt-head">Frequently Asked Questions</h1>
        @foreach(var x in Model.QuestionList){
        <div class="media blog-cmnt">
            <a href="javascript:;" class="pull-left">
                <img alt="" src="http://cdn.web-savvy-marketing.com/wp-content/uploads/2013/03/Question-Answer-300x225.jpg" class="media-object">
            </a>
            <div class="media-body">
                <h4 class="media-heading">
                    <span>@Html.ActionLink(x.Name, "AnswerQuestions", "FAQ", new { @id = x.Id }, new { @class = "label label-success" })</span>
                </h4>
                <div class="bl-status">
                    <span class="pull-left">@x.PostedQuestionDate</span>
                    <span>@Html.ActionLink("Archive", "ArchiveQuestion", "FAQ", new { @id = x.Id }, new { @class = "pull-right reply" })</span>
                </div>
                <p class="mp-less">
                    @x.QuestionText
                </p>
                @foreach(var z in x.QuestionAnswers){
                    <div class="media blog-cmnt">
                        <a href="javascript:;" class="pull-left">
                            <img alt="" src="images/blog/blog-avatar-2.jpg" class="media-object-child">
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading">
                                <a href="#">JMIBARRA</a>
                            </h4>
                            <div class="bl-status">
                                <span class="pull-left">@z.PostedAnswerDate</span>
                                <!--<a href="#" class="pull-right reply">Reply</a>-->
                            </div>
                            <p class="mp-less">
                                @z.AnswerText
                            </p>

                        </div>
                    </div>
                }
            </div>
        </div>
        }
    </div>
</div>